version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/cloudflare/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
