name = "tileservice"
main = "src/index.ts"
compatibility_date = "2024-09-02"
minify = false

r2_buckets  = [
  { binding = "BUCKET", bucket_name = "osmus-tile", preview_bucket_name = "osmus-tile" }
]

[vars]
ALLOWED_ORIGINS = "*"
CACHE_CONTROL = "public, max-age=3600"

# Rate limiter configuration
[[unsafe.bindings]]
name = "PER_USER_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 1000, period = 60 }

[[unsafe.bindings]]
name = "PER_ORIGIN_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1002"
simple = { limit = 30_000, period = 60 }
