title: OpenStreetMap US Tileservice
url: "http://localhost:4000"
liquid:
  error_mode: strict
  strict_variables: false
  strict_filters: true
source: _source
permalink: /:path/
date_format: "%b %e, %Y"
collections:
  pages:
    output: true
defaults:
  - scope:
      path: _pages
      type: pages
    values:
      permalink: /:path/
      layout: page