name: Deploy Website

on:
  push:
    branches: [main]
    paths: ['website/**']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: website
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          working-directory: website
          bundler-cache: true
          
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: website/viewer/package-lock.json

      - name: Install dependencies
        run: make deps

      - name: Build website
        run: make build

      - name: Install rclone
        run: sudo apt-get update && sudo apt-get install -y rclone

      - name: Setup rclone config
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONFIG }}" > ~/.config/rclone/rclone.conf

      - name: Deploy to Cloudflare R2
        run: rclone sync _site/ r2:osmus-tile/www/ --delete-excluded
